<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


### Basic Numpy Arrays

In [4]:
import sys
import numpy as np

In [14]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [180]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [104]:
b = np.array([5,6,7,8,9])
b

array([5, 6, 7, 8, 9])

In [106]:
a[3],a[4]

(4, 5)

In [108]:
b[0],b[-1],b[-2] # - reverse array and index to last on -1

(5, 9, 8)

In [110]:
b[[0,1,2]]

array([5, 6, 7])

### Array Types

In [113]:
a.dtype

dtype('int32')

In [118]:
c = np.array([1.0,2.5,5.0,7.5,10.0])
c.dtype

dtype('float64')

In [157]:
d = np.array([1,2,3,4,127], dtype=np.int8) 
#int 8 bits wont store more than 127
d

array([  1,   2,   3,   4, 127], dtype=int8)

### Dimensions and shapes

In [166]:
# Matricies and Shapes
A = np.array([
    [1,2,3],
    [4,5,6]
])

A.shape 
# 2 x 3 matrice array 2 row 3 columns 

(2, 3)

In [170]:
A.ndim # 2D Array

2

In [176]:
A.size # num of vals in array

6

In [182]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [198]:
B.shape

(2, 2, 3)

In [200]:
B.ndim # 3D Array

3

In [204]:
B.dtype

dtype('int32')